actions:
  - name: turnOffY3
    event:
      source: plchandler
      tag:
        name: GREEN
        value: 0
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: Y3
            value: 0
  - name: turnOnY3
    event:
      source: plchandler
      tag:
        name: GREEN
        value: 1
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: Y3
            value: 1
  - name: cardreader
    event:
      source: readerhandler
      tag:
        name: Reader0
        value: 10636976
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: Y3
            value: 1
      - name: delay
        params: 5
      - name: set
        command:
          destination: plchandler
          tag:
            name: Y3
            value: 0
