actions:
  - name: Van4Switch
    event:
      source: buttonshandler
      tag:
        name: Van1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: van4

  - name: Van2Switch
    event:
      source: buttonshandler
      tag:
        name: Van2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: van2

  - name: VanMainSwitchOff1
    event:
      source: buttonshandler
      tag:
        name: Van4Click
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: van4
          value: 1
      - source: plchandler
        tag:
          name: van2
          value: 1
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: van4
            value: 0
      - name: set
        command:
          destination: plchandler
          tag:
            name: van2
            value: 0

  - name: VanMainSwitchOff2
    event:
      source: buttonshandler
      tag:
        name: Van4Click
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: van4
          value: 0
      - source: plchandler
        tag:
          name: van2
          value: 1
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: van4
            value: 0
      - name: set
        command:
          destination: plchandler
          tag:
            name: van2
            value: 0

  - name: VanMainSwitchOff3
    event:
      source: buttonshandler
      tag:
        name: Van4Click
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: van4
          value: 1
      - source: plchandler
        tag:
          name: van2
          value: 0
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: van4
            value: 0
      - name: set
        command:
          destination: plchandler
          tag:
            name: van2
            value: 0

  - name: VanMainSwitchOn
    event:
      source: buttonshandler
      tag:
        name: Van4Click
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: van4
          value: 0
      - source: plchandler
        tag:
          name: van2
          value: 0
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: van4
            value: 1

  - name: Tamb1Switch
    event:
      source: buttonshandler
      tag:
        name: Tamb1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: kor

  - name: TambKorOnSwitch
    event:
      source: buttonshandler
      tag:
        name: KorClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: kor

  - name: Spa2Switch
    event:
      source: buttonshandler
      tag:
        name: Spa2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: spal

  - name: Spa1Switch
    event:
      source: buttonshandler
      tag:
        name: Spa1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: spal2

  - name: ZalSwitch
    event:
      source: buttonshandler
      tag:
        name: ZalClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: zal

  - name: GardSwitch
    event:
      source: buttonshandler
      tag:
        name: GardClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: gard

  - name: Tamb3Switch
    event:
      source: buttonshandler
      tag:
        name: Tamb3Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: tamb

  - name: Tamb2Switch
    event:
      source: buttonshandler
      tag:
        name: Tamb2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: ylic

  - name: KyhOn
    event:
      source: buttonshandler
      tag:
        name: KyhClick
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: kyh
          value: 0
      - source: plchandler
        tag:
          name: kyhup
          value: 0
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyh
            value: 1
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyhup
            value: 1

  - name: KyhOff1
    event:
      source: buttonshandler
      tag:
        name: KyhClick
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: kyh
          value: 1
      - source: plchandler
        tag:
          name: kyhup
          value: 0
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyh
            value: 0
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyhup
            value: 0

  - name: KyhOff2
    event:
      source: buttonshandler
      tag:
        name: KyhClick
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: kyh
          value: 0
      - source: plchandler
        tag:
          name: kyhup
          value: 1
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyh
            value: 0
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyhup
            value: 0

  - name: KyhOff3
    event:
      source: buttonshandler
      tag:
        name: KyhClick
        value: 1
    conditions:
      - source: plchandler
        tag:
          name: kyh
          value: 1
      - source: plchandler
        tag:
          name: kyhup
          value: 1
    commands:
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyh
            value: 0
      - name: set
        command:
          destination: plchandler
          tag:
            name: kyhup
            value: 0
