actions:
  - name: AllSwitchON
    event:
      source: buttonhandler
      tag:
        name: vkcEntrance1Click
        value: 1
    commands:
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: BoilerRoom
            # value: 1
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Entrance
            value: 1
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: Hallway
            # value: 1
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: WC
            # value: 1
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: BedRoomCeiling
            # value: 1
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: BedRoomBed
            # value: 1
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: LivingRoom
            # value: 1
  - name: Kids1Switch
    event:
      source: buttonhandler
      tag:
        name: vkcKids1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Kids1
            value: 1
  - name: Kids2Switch
    event:
      source: buttonhandler
      tag:
        name: vkcKids2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Kids2
            value: 1
  - name: GuestCeilingSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcGuestRoomCeilingClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: GuestCeiling
            value: 1
  - name: GuestTableSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcGuestRoomTableClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: GuestTable
            value: 1
  - name: BathRoomSwitch
    event:
      source: clickhandler
      tag:
        name: BathShortClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: BathRoom
            value: 1
      - name: invert
        command:
          destination: plchandler
          tag:
            name: BathRoomFun
            value: 1
  - name: BathRoomMirrorSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcBathRoomMirrorClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: BathRoomMirror
            value: 1
  # - name: BathRoomFunSwitch
    # event:
      # source: clickhandler
      # tag:
        # name: BathLongClick
        # value: 1
    # commands:
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: BathRoomFun
            # value: 1
  - name: KitchenSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcKitchenClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: KitchenTable
            value: 1
  - name: LivingRoom1Switch
    event:
      source: buttonhandler
      tag:
        name: vkcLivingRoom1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: LivingRoom
            value: 1
  - name: Hallway1Switch
    event:
      source: buttonhandler
      tag:
        name: vkcHallway2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Hallway
            value: 1
  - name: Hallway2RoomSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcLivingRoom2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: KitchenCeiling
            value: 1
      # - name: invert
        # command:
          # destination: plchandler
          # tag:
            # name: Hallway
            # value: 1
  - name: Stairs1Switch
    event:
      source: buttonhandler
      tag:
        name: vkcStairs1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Stairs
            value: 1
  - name: Stairs2RoomSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcStairs2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Stairs
            value: 1
  - name: WCSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcWCClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: WC
            value: 1
      - name: invert
        command:
          destination: plchandler
          tag:
            name: WCFun
            value: 1
  - name: ShowerRoomSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcShowerRoomClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: ShowerRoom
            value: 1
      - name: invert
        command:
          destination: plchandler
          tag:
            name: ShowerRoomFun
            value: 1
  - name: ShowerBoilerSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcBoilerRoomClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: BoilerRoom
            value: 1
  - name: BedroomCeilingSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcBedRoomCeiling2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: BedRoomCeiling
            value: 1
  - name: BedroomBedSwitch2
    event:
      source: buttonhandler
      tag:
        name: vkcBedRoomBed2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: BedRoomBed
            value: 1
  - name: Entrance2Switch
    event:
      source: buttonhandler
      tag:
        name: vkcEntrance2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Entrance
            value: 1
  - name: HallwaySwitch
    event:
      source: buttonhandler
      tag:
        name: vkcHallway1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Hallway
            value: 1
      - name: invert
        command:
          destination: plchandler
          tag:
            name: HallwayMirror
            value: 1
  - name: OutdoorSwitchOn
    event:
      source: buttonhandler
      tag:
        name: vkcOutdoor1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Outdoor1
            value: 1
  - name: OutdoorSwitchOff
    event:
      source: buttonhandler
      tag:
        name: vkcOutdoor1Click
        value: 0
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Outdoor1
            value: 1
  - name: OutdoorSwitch
    event:
      source: buttonhandler
      tag:
        name: vkcOutdoor2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: Outdoor1
            value: 1
