actions:
  - name: Van4Switch
    event:
      source: buttonshandler
      tag:
        name: Van1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: van4

  - name: Van2Switch
    event:
      source: buttonshandler
      tag:
        name: Van2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: van2

  - name: VanOnSwitch
    event:
      source: buttonshandler
      tag:
        name: Van4Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: van4

  - name: Tamb1Switch
    event:
      source: buttonshandler
      tag:
        name: Tamb1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: kor

  - name: TambKorOnSwitch
    event:
      source: buttonshandler
      tag:
        name: KorClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: kor

  - name: Spa2Switch
    event:
      source: buttonshandler
      tag:
        name: Spa2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: spal

  - name: Spa1Switch
    event:
      source: buttonshandler
      tag:
        name: Spa1Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: spal2

  - name: ZalSwitch
    event:
      source: buttonshandler
      tag:
        name: ZalClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: zal

  - name: GardSwitch
    event:
      source: buttonshandler
      tag:
        name: GardClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: gard

  - name: Tamb3Switch
    event:
      source: buttonshandler
      tag:
        name: Tamb3Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: tamb

  - name: Tamb2Switch
    event:
      source: buttonshandler
      tag:
        name: Tamb2Click
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: ylic

  - name: KyhSwitch
    event:
      source: buttonshandler
      tag:
        name: KyhClick
        value: 1
    commands:
      - name: invert
        command:
          destination: plchandler
          tag:
            name: kyh
      - name: invert
        command:
          destination: plchandler
          tag:
            name: kyhup
