clicks:
  - name: BathLongClick
    event:
      source: buttonhandler
      tag:
        name: vkcBathRoomClick
        value: 1
    on_release: true
    timeout: 500
  - name: BathShortClick
    event:
      source: buttonhandler
      tag:
        name: vkcBathRoomClick
        value: 1
    timeout: 10
    on_release: true
