handlers:
  - name: dummyhandler
    run: yes
  - name: plchandler
    run: no
  - name: actionhandler
    run: yes
  - name: readerhandler
    run: no
  - name: loghandler
    run: yes
  - name: doorhandler
    run: yes
  - name: accesshandler
    run: yes
