token: 
tags:
  - source: dummyhandler
    tag:
      name: BoilerRoom
  - source: dummyhandler
    tag:
      name: BathRoom
  - source: dummyhandler
    tag:
      name: BathRoomMirror
  - source: dummyhandler
    tag:
      name: BathRoomFun
  - source: dummyhandler
    tag:
      name: GuestCeiling
  - source: dummyhandler
    tag:
      name: GuestTable
  - source: dummyhandler
    tag:
      name: Entrance
  - source: dummyhandler
    tag:
      name: HallwayMirror
  - source: dummyhandler
    tag:
      name: Hallway
  - source: dummyhandler
    tag:
      name: BedRoomCeiling
  - source: dummyhandler
    tag:
      name: BedRoomBed
  - source: dummyhandler
    tag:
      name: Kids1
  - source: dummyhandler
    tag:
      name: Kids2
  - source: dummyhandler
    tag:
      name: Cabinet
  - source: dummyhandler
    tag:
      name: KitchenCeiling
  - source: dummyhandler
    tag:
      name: KitchenTable
  - source: dummyhandler
    tag:
      name: LivingRoom
  - source: dummyhandler
    tag:
      name: LivingRoom2
  - source: dummyhandler
    tag:
      name: Outdoor1
  - source: dummyhandler
    tag:
      name: Outdoor2
  - source: dummyhandler
    tag:
      name: Outdoor3
  - source: dummyhandler
    tag:
      name: facade
  - source: dummyhandler
    tag:
      name: Balcony
  - source: dummyhandler
    tag:
      name: Stairs
  - source: dummyhandler
    tag:
      name: ShowerRoomMirror
  - source: dummyhandler
    tag:
      name: Gates
  - source: dummyhandler
    tag:
      name: ShowerRoom
  - source: dummyhandler
    tag:
      name: ShowerRoomFun
  - source: dummyhandler
    tag:
      name: WC
  - source: dummyhandler
    tag:
      name: WCFun
