proxy:
  address: proxy.aborilov.ru:7777
  username: sockduser
  password: aborilov
token: 468935138:AAEgdl3Pi28dUAfEp5N-Rn1v_NxkBbve_go
tags:
  - source: plchandler
    tag:
      name: kyh
  - source: plchandler
    tag:
      name: kyhup
  - source: plchandler
    tag:
      name: van4
  - source: plchandler
    tag:
      name: van2
  - source: plchandler
    tag:
      name: spal
  - source: plchandler
    tag:
      name: spal2
  - source: plchandler
    tag:
      name: tamb
  - source: plchandler
    tag:
      name: ylic
  - source: plchandler
    tag:
      name: gard
  - source: plchandler
    tag:
      name: kor
